/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PricePlanRouteImport } from './routes/price-plan'
import { Route as ServiceDetailsRouteImport } from './routes/service-details'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as ServicesAdvancedAestheticsRouteImport } from './routes/services/advanced-aesthetics'
import { Route as ServicesBeautyAtelierRouteImport } from './routes/services/beauty-atelier'
import { Route as ServicesSkinAndBodyRitualsRouteImport } from './routes/services/skin-and-body-rituals'
import { Route as ServicesSpaPackagesRouteImport } from './routes/services/spa-packages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricePlanRoute = PricePlanRouteImport.update({
  id: '/price-plan',
  path: '/price-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDetailsRoute = ServiceDetailsRouteImport.update({
  id: '/service-details',
  path: '/service-details',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdvancedAestheticsRoute =
  ServicesAdvancedAestheticsRouteImport.update({
    id: '/services/advanced-aesthetics',
    path: '/services/advanced-aesthetics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBeautyAtelierRoute = ServicesBeautyAtelierRouteImport.update({
  id: '/services/beauty-atelier',
  path: '/services/beauty-atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSkinAndBodyRitualsRoute =
  ServicesSkinAndBodyRitualsRouteImport.update({
    id: '/services/skin-and-body-rituals',
    path: '/services/skin-and-body-rituals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSpaPackagesRoute = ServicesSpaPackagesRouteImport.update({
  id: '/services/spa-packages',
  path: '/services/spa-packages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/price-plan': typeof PricePlanRoute
  '/service-details': typeof ServiceDetailsRoute
  '/team': typeof TeamRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/price-plan': typeof PricePlanRoute
  '/service-details': typeof ServiceDetailsRoute
  '/team': typeof TeamRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/price-plan': typeof PricePlanRoute
  '/service-details': typeof ServiceDetailsRoute
  '/team': typeof TeamRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/gallery'
    | '/price-plan'
    | '/service-details'
    | '/team'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/gallery'
    | '/price-plan'
    | '/service-details'
    | '/team'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/gallery'
    | '/price-plan'
    | '/service-details'
    | '/team'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PricePlanRoute: typeof PricePlanRoute
  ServiceDetailsRoute: typeof ServiceDetailsRoute
  TeamRoute: typeof TeamRoute
  TreatmentsRoute: typeof TreatmentsRoute
  ServicesAdvancedAestheticsRoute: typeof ServicesAdvancedAestheticsRoute
  ServicesBeautyAtelierRoute: typeof ServicesBeautyAtelierRoute
  ServicesSkinAndBodyRitualsRoute: typeof ServicesSkinAndBodyRitualsRoute
  ServicesSpaPackagesRoute: typeof ServicesSpaPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-plan': {
      id: '/price-plan'
      path: '/price-plan'
      fullPath: '/price-plan'
      preLoaderRoute: typeof PricePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-details': {
      id: '/service-details'
      path: '/service-details'
      fullPath: '/service-details'
      preLoaderRoute: typeof ServiceDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/advanced-aesthetics': {
      id: '/services/advanced-aesthetics'
      path: '/services/advanced-aesthetics'
      fullPath: '/services/advanced-aesthetics'
      preLoaderRoute: typeof ServicesAdvancedAestheticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/beauty-atelier': {
      id: '/services/beauty-atelier'
      path: '/services/beauty-atelier'
      fullPath: '/services/beauty-atelier'
      preLoaderRoute: typeof ServicesBeautyAtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/skin-and-body-rituals': {
      id: '/services/skin-and-body-rituals'
      path: '/services/skin-and-body-rituals'
      fullPath: '/services/skin-and-body-rituals'
      preLoaderRoute: typeof ServicesSkinAndBodyRitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/spa-packages': {
      id: '/services/spa-packages'
      path: '/services/spa-packages'
      fullPath: '/services/spa-packages'
      preLoaderRoute: typeof ServicesSpaPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PricePlanRoute: PricePlanRoute,
  ServiceDetailsRoute: ServiceDetailsRoute,
  TeamRoute: TeamRoute,
  TreatmentsRoute: TreatmentsRoute,
  ServicesAdvancedAestheticsRoute: ServicesAdvancedAestheticsRoute,
  ServicesBeautyAtelierRoute: ServicesBeautyAtelierRoute,
  ServicesSkinAndBodyRitualsRoute: ServicesSkinAndBodyRitualsRoute,
  ServicesSpaPackagesRoute: ServicesSpaPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
