/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as ServicesAdvancedAestheticsRouteImport } from './routes/services/advanced-aesthetics'
import { Route as ServicesBeautyAtelierRouteImport } from './routes/services/beauty-atelier'
import { Route as ServicesSkinAndBodyRitualsRouteImport } from './routes/services/skin-and-body-rituals'
import { Route as ServicesSpaPackagesRouteImport } from './routes/services/spa-packages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdvancedAestheticsRoute =
  ServicesAdvancedAestheticsRouteImport.update({
    id: '/services/advanced-aesthetics',
    path: '/services/advanced-aesthetics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBeautyAtelierRoute = ServicesBeautyAtelierRouteImport.update({
  id: '/services/beauty-atelier',
  path: '/services/beauty-atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSkinAndBodyRitualsRoute =
  ServicesSkinAndBodyRitualsRouteImport.update({
    id: '/services/skin-and-body-rituals',
    path: '/services/skin-and-body-rituals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSpaPackagesRoute = ServicesSpaPackagesRouteImport.update({
  id: '/services/spa-packages',
  path: '/services/spa-packages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/treatments': typeof TreatmentsRoute
  '/services/advanced-aesthetics': typeof ServicesAdvancedAestheticsRoute
  '/services/beauty-atelier': typeof ServicesBeautyAtelierRoute
  '/services/skin-and-body-rituals': typeof ServicesSkinAndBodyRitualsRoute
  '/services/spa-packages': typeof ServicesSpaPackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/treatments'
    | '/services/advanced-aesthetics'
    | '/services/beauty-atelier'
    | '/services/skin-and-body-rituals'
    | '/services/spa-packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  TreatmentsRoute: typeof TreatmentsRoute
  ServicesAdvancedAestheticsRoute: typeof ServicesAdvancedAestheticsRoute
  ServicesBeautyAtelierRoute: typeof ServicesBeautyAtelierRoute
  ServicesSkinAndBodyRitualsRoute: typeof ServicesSkinAndBodyRitualsRoute
  ServicesSpaPackagesRoute: typeof ServicesSpaPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/advanced-aesthetics': {
      id: '/services/advanced-aesthetics'
      path: '/services/advanced-aesthetics'
      fullPath: '/services/advanced-aesthetics'
      preLoaderRoute: typeof ServicesAdvancedAestheticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/beauty-atelier': {
      id: '/services/beauty-atelier'
      path: '/services/beauty-atelier'
      fullPath: '/services/beauty-atelier'
      preLoaderRoute: typeof ServicesBeautyAtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/skin-and-body-rituals': {
      id: '/services/skin-and-body-rituals'
      path: '/services/skin-and-body-rituals'
      fullPath: '/services/skin-and-body-rituals'
      preLoaderRoute: typeof ServicesSkinAndBodyRitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/spa-packages': {
      id: '/services/spa-packages'
      path: '/services/spa-packages'
      fullPath: '/services/spa-packages'
      preLoaderRoute: typeof ServicesSpaPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  TreatmentsRoute: TreatmentsRoute,
  ServicesAdvancedAestheticsRoute: ServicesAdvancedAestheticsRoute,
  ServicesBeautyAtelierRoute: ServicesBeautyAtelierRoute,
  ServicesSkinAndBodyRitualsRoute: ServicesSkinAndBodyRitualsRoute,
  ServicesSpaPackagesRoute: ServicesSpaPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
